// <auto-generated />
using System;
using Fiap.coleta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.coleta.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240627022213_AddAddress")]
    partial class AddAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.coleta.Models.AddressModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("complement")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("date");

                    b.Property<string>("neighborhood")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("number")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Fiap.coleta.Models.ResidentModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("address_id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.HasIndex("address_id");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("Fiap.coleta.Models.ResidentModel", b =>
                {
                    b.HasOne("Fiap.coleta.Models.AddressModel", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
